### PR TITLE
Allow more changes to AuditD

### PR DESCRIPTION
**Pull request by tdekoning93**
Hey! 

I'm basically copying the PR of @DeWaRs1206.
https://github.com/dev-sec/chef-os-hardening/pull/307

Seems he abandoned ship. I really need this though, since we want to change same auditd parameters that currently can't be set. I've changed the attributes mentioned in the comments on that PR to what they should be.

### CODE REVIEW

**Comment by tdekoning93** [comment]
Highly appreciated if you could have a look @artem-sidorenko

**Comment by schurzi** [comment]
@tdekoning93 changes and tests looking good, can you solve the cookstyle issues, then I will merge it.

**Comment by tdekoning93** [comment]
Done @schurzi

**Comment by tdekoning93** [comment]
@schurzi Thanks for merging! Can you also maybe make a new release? Currently I'm still grabbing latest, which is 4.1.2

**Comment by schurzi** [comment]
> @schurzi Thanks for merging! Can you also maybe make a new release? Currently I'm still grabbing latest, which is 4.1.2

v4.2.0 is released now

**Comment by artem-sidorenko** [comment]
@schurzi many thanks for taking care :)

**Pull request merged**
