### PR TITLE
Ubuntu 18.04 is supported

### PR DESCRIPTION
**Pull request by frederikbosch**
Update README.md to include support for Ubuntu 18.04.

### CODE REVIEW

**Comment by frederikbosch** [comment]
I see that Ubuntu 18.04 is included in Travis (with no specific config for allowed errors). I guess it means that 18.04 is supported. This PR adds 18.04 to the readme.

**Comment by artem-sidorenko** [comment]
@frederikbosch there are still some errors which needs to be fixed: 

- https://travis-ci.org/dev-sec/chef-os-hardening/builds/408672521
- https://travis-ci.org/dev-sec/chef-os-hardening/jobs/408672545

:-(

**Comment by frederikbosch** [comment]
Thanks. Is it correct that these are the two failures?
- [ ] os-11: Protect log-directory (1 failed). Test: File /var/log should be grouped into "syslog
- [ ] Recipe: os-hardening::pam (tally2)

**Comment by frederikbosch** [comment]
If so, I'll look into the errors and see if I can fix them.

**Comment by artem-sidorenko** [comment]
@frederikbosch I saw only the log permissions failure, but maybe I missed something else.

**Comment by frederikbosch** [comment]
@artem-sidorenko Alright, I'll see what I can do to update this PR to include full support of Ubuntu 18.04.

**Comment by artem-sidorenko** [comment]
@frederikbosch great! Thank you!

**Comment by frederikbosch** [comment]
This PR is updated. First, I have created a fix in the baseline package, see [#100](https://github.com/dev-sec/linux-baseline/pull/100). That PR fixes all the tests for 18.04 here, and also the allowed failure of  `INSTANCE=ubuntu-16-04 KITCHEN_LOCAL_YAML=.kitchen.dokken.yml` for Ubuntu 16.04.

Please be aware that **this PR uses my forked baseline package in the inspec dependencies** to run the tests against. After merging the baseline fix, this PR has to be updated and restore the dependency.

@artem-sidorenko I would love to see the PR at the baseline merged, then we can update and merge this PR too.

**Comment by artem-sidorenko** [comment]
@frederikbosch I'm currently not sure how to resolve it or what the reason is there for a missing rsyslog installation. I try to have a deeper look here in the next days

**Comment by artem-sidorenko** [comment]
@frederikbosch btw, thanks for your work!

**Comment by artem-sidorenko** [comment]
@frederikbosch thank you!

**Pull request merged**
