### PR TITLE
RH family: adapt some settings, as RH has better defaults

### PR DESCRIPTION
**Pull request by artem-sidorenko**
https://github.com/dev-sec/linux-baseline/pull/82

Its WIP as the linux-baseline PR is not merged yet

### CODE REVIEW

**Comment by shoekstra** [comment]
Hi @artem-sidorenko,

Is this ready to merge?  the linux-baseline PR has been merged and the puppet and ansible one are done, would be good to get these fixes into the Supermarket.

Cheers,

**Comment by artem-sidorenko** [comment]
@shoekstra I want to add the fix with log permissions (see CI details) here in order to get the CI tests green. I'll do that as soon as I have time, hopefully this week.

**Comment by shoekstra** [comment]
Hi @artem-sidorenko, as this PR only addresses rhel related updates in dev-sec/linux-baseline#82 I would be in favour of merging this as is because the related tests are passing and then fixing the non-rhel failed tests in a separate PR, something I'm happy to help with if you like?  Alternatively I could create a separate PR for the non-rhel tests so long and then merge them all when ready?

Thoughts?

**Comment by artem-sidorenko** [comment]
@shoekstra fair enough. Would you provide another PR, which fixes the failing log-related things? If yes, I would merge this PR

**Comment by shoekstra** [comment]
@artem-sidorenko yup!

**Comment by artem-sidorenko** [comment]
@shoekstra here you are:-)

**Comment by shoekstra** [comment]
I'll get started then 😃   Thanks!

**Pull request merged**
