### PR TITLE
add spellchecking with codespell

### PR DESCRIPTION
**Pull request by schurzi**

### CODE REVIEW

**Comment by schurzi** [comment]
@artem-sidorenko I have correted the past PRs so the Changelog will be regenerated with the corrections applied. Merging is up to oyu, since you are active here at the moment. I have added the Action to the security list, hope that is ok.

**Comment by artem-sidorenko** [comment]
@schurzi many thanks! The intention is to run it on the master branch? Any idea how this is going to work with changelog generator, hence the source are issues/prs and not the file on the master branch?

**Comment by schurzi** [comment]
This configuration will check all PRs directed on master and all direct commits done on master. My thought was, that the automatic changelog generator will update the file on master branch and when there are spelling errors a maintainer will get a mail with the failed checks. Then we would need to correct the spelling in the offending issue/pr and the next time, the changelog is generated, it is fixed. I know this is not optimal, but I have no better approach to check all issue and pr titles before generating the changelog and checking it into master.MAybe we can improve the workflow, once we have more experience with it :)

**Comment by schurzi** [comment]
Yes. The current config defines it as part of PR workflow. The spellcheck will run with every PR that is opened on master and will prevent new spelling errors from files in commits.

see for example here: https://github.com/dev-sec/ansible-collection-hardening/pull/667/checks

**Comment by artem-sidorenko** [comment]
@schurzi many thanks for you all your explanations :-) I see, somebody already fixed the PR titles😁

**Pull request merged**
